Add Nuxt 3 example
bufbuild/connect-web-integration pull request #193
Opened 2022-12-03 21:41 UTC by wobsoriano

Adds a Basic Nuxt example. Basically converted the Nextjs demo to Nuxt.

2022-12-03 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bufbuild/connect-web-integration?pullRequest=193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bufbuild/connect-web-integration?pullRequest=193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bufbuild/connect-web-integration?pullRequest=193) it.</sub>

2022-12-06 02:21 UTC, smaye81 commented
Hey @wobsoriano thanks for the PR!  Left a few small comments.  Also two small overall comments:

- Please add a description of this directory to the main README.  You can follow the examples there.
- Please add a command to `update.sh` at the project root for updating the @bufbuild deps for this project.  You'll see the other examples, should be pretty self-explanatory.

2022-12-06 02:21 UTC, smaye81 requested changes

2022-12-06 02:21 UTC, smaye81 commented on nuxt/.gitignore
> +node_modules
Can you remove this and add these to the main `.gitignore` at the project root?

2022-12-06 02:21 UTC, smaye81 commented on nuxt/package.json
> +    "build": "nuxt build",
Can you add a step here to the build for compiling TypeScript?

2022-12-13 06:26 UTC, wobsoriano commented on nuxt/.gitignore
> +node_modules
Removed. `node_modules` already in project root :)

2022-12-13 06:26 UTC, wobsoriano commented on nuxt/package.json
> +  "devDependencies": {
Updated and ran `buf:generate` again.

2022-12-13 06:32 UTC, wobsoriano commented on nuxt/package.json
> +    "build": "nuxt build",
Do we have a sample of this in other examples?

2022-12-13 15:00 UTC, smaye81 commented on nuxt/package.json
> +    "build": "nuxt build",
Yep, there's a few.  Take a look at the [package.json](https://github.com/bufbuild/connect-web-integration/blob/main/react/vite/package.json#L8) in `react/vite` for a similar example.

2023-02-02 01:58 UTC, smaye81 commented on nuxt/package.json
> +    "build": "nuxt build",
@wobsoriano Just checking in.  Any update?

2023-02-02 04:56 UTC, wobsoriano commented on nuxt/package.json
> +    "build": "nuxt build",
Hey, got busy. Will defo update tom 👍🏼

2023-02-02 21:58 UTC, closed without merging

2024-10-10 12:14 UTC, 4F2E4A2E commented
Can we still have a nuxt example?